name: GitHub Metrics
on:
  # Atualiza automaticamente todo dia à meia-noite
  schedule: [{cron: "0 0 * * *"}]
  # Permite que você rode manualmente na aba "Actions" para testar
  workflow_dispatch:
  # Roda sempre que você fizer um push na branch principal
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Personal Metrics
        uses: lowlighter/metrics@latest
        with:
          # O nome do Secret (METRICS_TOKEN)
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Configurações de exibição
          user: Wemers0n
          template: classic
          base: header, community, repositories, metadata
          
          # Plugins extras (opcionais, mas legais)
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_habits: yes
          plugin_habits_factoids: yes
          
          # Fuso horário para os gráficos de hábitos
          config_timezone: America/Sao_Paulo
